require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategoriesController do

  def mock_categorie(stubs={})
    @mock_categorie ||= mock_model(Categorie, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all categories as @categories" do
      Categorie.stub(:all) { [mock_categorie] }
      get :index
      assigns(:categories).should eq([mock_categorie])
    end
  end

  describe "GET show" do
    it "assigns the requested categorie as @categorie" do
      Categorie.stub(:find).with("37") { mock_categorie }
      get :show, :id => "37"
      assigns(:categorie).should be(mock_categorie)
    end
  end

  describe "GET new" do
    it "assigns a new categorie as @categorie" do
      Categorie.stub(:new) { mock_categorie }
      get :new
      assigns(:categorie).should be(mock_categorie)
    end
  end

  describe "GET edit" do
    it "assigns the requested categorie as @categorie" do
      Categorie.stub(:find).with("37") { mock_categorie }
      get :edit, :id => "37"
      assigns(:categorie).should be(mock_categorie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created categorie as @categorie" do
        Categorie.stub(:new).with({'these' => 'params'}) { mock_categorie(:save => true) }
        post :create, :categorie => {'these' => 'params'}
        assigns(:categorie).should be(mock_categorie)
      end

      it "redirects to the created categorie" do
        Categorie.stub(:new) { mock_categorie(:save => true) }
        post :create, :categorie => {}
        response.should redirect_to(category_url(mock_categorie))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categorie as @categorie" do
        Categorie.stub(:new).with({'these' => 'params'}) { mock_categorie(:save => false) }
        post :create, :categorie => {'these' => 'params'}
        assigns(:categorie).should be(mock_categorie)
      end

      it "re-renders the 'new' template" do
        Categorie.stub(:new) { mock_categorie(:save => false) }
        post :create, :categorie => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested categorie" do
        Categorie.stub(:find).with("37") { mock_categorie }
        mock_category.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :categorie => {'these' => 'params'}
      end

      it "assigns the requested categorie as @categorie" do
        Categorie.stub(:find) { mock_categorie(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:categorie).should be(mock_categorie)
      end

      it "redirects to the categorie" do
        Categorie.stub(:find) { mock_categorie(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(category_url(mock_categorie))
      end
    end

    describe "with invalid params" do
      it "assigns the categorie as @categorie" do
        Categorie.stub(:find) { mock_categorie(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:categorie).should be(mock_categorie)
      end

      it "re-renders the 'edit' template" do
        Categorie.stub(:find) { mock_categorie(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categorie" do
      Categorie.stub(:find).with("37") { mock_categorie }
      mock_category.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the categories list" do
      Categorie.stub(:find) { mock_categorie }
      delete :destroy, :id => "1"
      response.should redirect_to(categories_url)
    end
  end

end
